### PR TITLE
add more ecmcEcSlave.template, rename ecmcDS.template

### PR DESCRIPTION
**Pull request by jeonghanlee**
@anderssandstrom 
Please look at this pull request, I did look at all substitutions again, and added 
```
file "ecmcEcSlave.template"
{
  pattern {}
          {}
}
```

In addition,  https://github.com/icshwi/ecmccfg/blob/master/db/MicroEpsilon/capaNCDT6500.substitutions doesn't have it. Do we need it to there?

### CODE REVIEW

**Comment by anderssandstrom** [comment]
@jeonghanlee, thanks for looking into this. The EL37X2*.subst and EL10X8.subst is obsolete (probably old files from ecmccfg not removed after merge of ecmctraining 6.0.0).
The NDCT6500 should have the ecmcEcSlave.template in subst. file.

**Comment by jeonghanlee** [comment]
@anderssandstrom  I removed old files, and add ecmcEcSlave.template into capaNDC*.sub file. Please let me know what you think.

**Comment by anderssandstrom** [comment]
@jeonghanlee, wrong file deleted. The ecmcEL1018.substitutions is valid. The ecmcEL10X8.substitutions should be removed.

**Comment by jeonghanlee** [comment]
@anderssandstrom , please review this change.

**Pull request merged**
