### PR TITLE
Fix ess naming

### PR DESCRIPTION
**Pull request by javicereijo**
Hi Anders, here is a merge request to try to fit better to the ESS naming convention. The first 2 commits should be quite acceptable in my opinion, as the default build after inflating the dbs doesn't change, but maybe you want to improve the name of the macro.
The last commit may be breaking some IOCs so probably needs more attention and discussion with PSI, so I understand if you don't accept it. The reasoning for it is that, according to our naming convention, the property part of the PV names should be no longer than 20 characters ideally, and never longer than 25. These 2 records have too long names to fit to this rule easily. The record name ${ECMC_P}Enc${CH_ID}-LtchAutRstSp in db/Beckhoff_5XXX/ecmcEL5101-chX.template is also a little bit too long but we can adapt to it.
Thank you,
Javier

### CODE REVIEW

**Comment by anderssandstrom** [comment]
Hi Javier,

Thanks a lot for the MR!

**First commit:**
Looks fine, no problem!
**Second commit:**
All current systems then need to start using the ess long naming since the slave id is changed to 2 digits in the "normal" essnaming, right?
**Third commit:**
I think the name you came up with is much better and shorter so that's great!

Within short we will need to make a new major release of ecmc and ecmccfg. This mainly because ecmc will have a new dependency on ruckig (used for adding s-curve trajectories to ecmc) and we will also support motion directly from non motor record pv:s. So, I would suggest to make this merge into ruckig branch instead, because then we can describe the changes in the release notes. How urgent would you say this is for you? 

@kivel, do you have any comments on this mr/pr?

cheers
Anders

**Comment by kivel** [comment]
As you pointed out, the 3rd commit is breaking. Thus, I prefer to merge this into the upstream `v8_RC1` branch, as this is the WIP branch for all changes associated with the `ruckig` branch of ECMC ... which will be released as v8.

**Comment by javicereijo** [comment]
@kivel Yes, it's fine to merge this into `v8_RC1` and get these commits in the v8 release.
@anderssandstrom This is not urgent at all, so don't worry. About the naming, I think it's up to the integrator/developer to choose the long or short (default) version. As far as I know it's only one system at ESS that has or will have more than 100 slaves, so almost all of our systems could potentially use the short version. This change could in fact create some problems for us right now but I know all the systems that would be affected, and the solution is also very easy. But if this change goes directly into the next major version then it would indeed be more clear.

Do you want me to modify this merge request to point to any specific branch? The options seem to be the `ruckig` branch in the ESS fork or `v8_RC1` in the PSI one. Or feel free to modify the merge request yourselves if you prefer.

**Comment by anderssandstrom** [comment]
@javicereijo, yes agree, I guess there will not be many systems over 100 slaves. The problems you refer to is that defaulting to short naming will break all ioc:s not only the once with high slave count since GUIs and PVs reading or writing from ecmc pvs will expect the long format, right?! But I guess that is not a big problem since not many ioc:s have migrated to ecmc 7 yet.
 I can merge into ess/ruckig then I make a pr to psi/v8_RC1

**Comment by javicereijo** [comment]
Hi @anderssandstrom yes that's was I meant when I said I know all of the IOCs that are using v7.
But I have had a discussion with Alfio and maybe we can fix in some other way on our side without changing any PV names. So for now I will modify this merge request to only include the first commit and we can have a more in depth talk with Alfio about the other parts.

**Comment by javicereijo** [comment]
Sorry, I will close this merge request for now and open a new one for the first commit.
Sorry for the spam!

**Pull request closed without merging**
